### ISSUE TITLE
Existing integration does not have Energy Sector

### ISSUE THREAD

**Issue by nromyn** [N3rdP1um23/ontario_energy_board#2]
When a pre-existing energy source is configured, the integration fails to load. 

Repro: 
1. Using main branch, configure an entry for "GrandBridge Energy Inc.-Energy+ Rate Zone (RESIDENTIAL) Rate"
2. Overwrite custom_components/ontario_energy_board with the dev branch
3. Reload homeassistant

```
This error originated from a custom integration.

Logger: custom_components.ontario_energy_board.coordinator
Source: helpers/update_coordinator.py:315
integration: Ontario Energy Board (documentation, issues)
First occurred: 09:11:05 (6 occurrences)
Last logged: 09:12:25

Unexpected error fetching ontario_energy_board data: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ontario_energy_board/coordinator.py", line 66, in _async_update_data
    company_energy_sector = company_energy_sector_search.group(1)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

```

**Comment by nromyn** [comment]
Irrelevant. From the fine PR:

>    Users will have to select their electricity companies again as the entity id has changed to include the energy sector

**Comment by nromyn** [comment]
Irrelevant. From the fine PR:

>    Users will have to select their electricity companies again as the entity id has changed to include the energy sector
